name: Update Paper List
on:
  workflow_dispatch:
  schedule:
    - cron: 37 11 * * *
  push:
    branches:
      - master

permissions:
  contents: write
  
jobs:
  update_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - name: Install
        run: |
          pip install -r requirements.txt
      - name: Run
        run: |
          python main.py
      - name: Commit
        run: |
          if git diff --quiet -- readme.md; then
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add readme.md
          git commit -m "Updated paper list"
          git push
